spring:
  profiles:
    include:
      - aws
      - oauth
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  session:
    store-type: jdbc

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
